[project]
name = "csig"
version = "0.1.2"
description = "Implementation of AWS Signature Version 4"
readme = "README.md"
requires-python = ">=3.8"

[dependency-groups]
dev = [
    "botocore>=1.37.38",
    "ruff>=0.14.9",
    "ty>=0.0.1a34",
    "freezegun>=1.5.5",
]
